apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: false
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRXZtYzRaWWFpaW93RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1UVXdPREExTVRsYUZ3MHpOVEV4TVRNd09ERXdNVGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURBdm91bnBKTE9RaHF6TGFDRWx5QVVNWlc2L3FmMU1aUDFwelhubjdocm5hc3g1czJacU1iME9ycEkKU0JVand0dGdJMTczdVBFcG83aFpjRVdtSGtta3FKY1lhbmw2RStnWlBGeFFnK1lKTnBWYnZqQ3cxZ1JPN1hvZApxTjRLS25zVUliVWJRRzZkU2gxTFRmMHVhOEhZVEFzbDlocGdiKzloaEpKV1JLeC9pcXUzbGlLY3lwcnVkUHp5CnkxNkJNWXlEdFVhczIrd3d4anhHQ2tVbDhzQ2h1UHRNOSs0MENZT0tXUytJWG90bVRHUmdYMWVsazBvZHhDUUIKU0QxcVlVSngvQS9LQmk0QUNyOHZEVndPN2ZtTnRVTklRYUt6cVNjVnVvcXB5QlVjcEE4YUo1YWJnMHdmaE5jTQpGR1J4TUJ0MU5GYndxSDdtdXdMbUVHWnl0eFdmQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUQ21aZ0hqNFJVSlhvUWxzVjdTbGNYdlRPMU1qQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVF3ZUovT2kvRQo2V1B5N29ES2ZMeXFxNlEzZU5MeGdYcmNaa1dFT2g2VjFsOHljZ1JEV2R1NHpaSlRHV3pjNXYxTXp6dUFFanZRCjZveFpuVG9OcDBxZy93NHVvczlTWnFPT3RvaDRhaXRUVkx1cEtTOWlFMzFzM1hQQlExKzVzUm5udlFiMTNxeUcKVnBRRjliQVJxbUQ5MVExZ28zZXlxUUIzTFk3MVBVUDdpeTMyWWwyR1FVTmR5WXlSNFBnbWRTTW1JQTlhUnVHZQpIRWVhS0VkejhnT2RoUXpFZkZvc2p1aUJyTmI4aGlqbVFlWk0ySk9SRlRMbVVCQ3hzVU1WeDUxeU96V0RpOUpLCjkxRURrN1BkNGJPOWdMZTZsdnA0Q3NpMlJIZHN0SXZTcVpNYzBFbmZWcUZRY2ZRZVNYQnRtcTNjSzczN1g1VVoKaXk3NnZvUjYyWFBaCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://hcp-d8236e2b-b011-4006-b13e-9730aa1a0b74.spot.rackspace.com/
    name: phltraining2022-22
contexts:
  - context:
      cluster: phltraining2022-22
      namespace: default
      user: ngpc-user
    name: live1-phltraining2022-22
  - context:
      cluster: phltraining2022-22
      namespace: default
      user: oidc
    name: live1-phltraining2022-22-oidc
current-context: live1-phltraining2022-22
kind: Config
preferences: {}
users:
  - name: ngpc-user
    user:
      token: >-
        eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNYQ25nd1NFS0JWQl9DbWxvalo0eCJ9.eyJncm91cCI6ImNsb3Vkc3BhY2UtYWRtaW4iLCJnaXZlbl9uYW1lIjoiTGl2ZSIsImZhbWlseV9uYW1lIjoiT25lIiwibmlja25hbWUiOiJwaGx0cmFpbmluZzIwMjIiLCJuYW1lIjoiTGl2ZSBPbmUiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jSlZ1Q1Blb2MzRW5JYW5ESFdLM0JRdkdrTFdkNGFlVlhjcFhWdng4LWVFLXI5bEtnPXM5Ni1jIiwidXBkYXRlZF9hdCI6IjIwMjUtMTEtMTVUMTM6MzQ6NDkuMjc5WiIsImVtYWlsIjoicGhsdHJhaW5pbmcyMDIyQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2xvZ2luLnNwb3QucmFja3NwYWNlLmNvbS8iLCJhdWQiOiJtd0czbFVNVjhLeWVNcUhlNGZKNUJiM25NMXZCdlJOYSIsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTAwOTQ2OTUxNzE2MDIxMzA4MTkxIiwiaWF0IjoxNzYzMjE0NjY2LCJleHAiOjE3NjM0NzM4NjYsInNpZCI6Im5GeHhDMG5YY0x1QVVaZDVtUUVsV3F2V2h3WUlPR3lJIiwibm9uY2UiOiJRM0J4WVZsbk9FdFhSMDFrTG5aT05sOVZYMGx6YW5VeFNHbHpkVmxKVERrNU0wUmhkRmQzVkhKSVZBPT0iLCJvcmdfaWQiOiJvcmdfM2tMUmlMZmpzMmU1VGFWciJ9.TgI8vMY9Xwd4VqAxRYWBItk6hlqxduJbDDaCmh78MMbd8voJR3SsouJPAk0ThgseDC_c2dVG6Oi5U4bbJGbgdMWZN58BT0m8hQ-3W7GQ9xKiQy6Rta222e3-Re4EnQnQC_m-2z9TXEN351PE3wtxxmgDsQ-mxoxSPGe6OSkqvEUGLSNt95RBkQnNJ0NGA039pxWBpYxHsXnoIwQJ-AUJQjHgz9oN6hUNlviAgaH5LFX9Rgv498ZYtM3SxlhDh2nnW44_hYlV6DbG18XWkazaL_KeSWAZ_2Ip60Y70pABP3L89n4cPwS-e7snoWHC_kU-Linp9vX_gxd1iXuqJjKCKw
  - name: oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - '--oidc-issuer-url=https://login.spot.rackspace.com/'
          - '--oidc-client-id=mwG3lUMV8KyeMqHe4fJ5Bb3nM1vBvRNa'
          - '--oidc-extra-scope=openid'
          - '--oidc-extra-scope=profile'
          - '--oidc-extra-scope=email'
          - '--oidc-auth-request-extra-params=organization=org_3kLRiLfjs2e5TaVr'
          - '--token-cache-dir=~/.kube/cache/oidc-login/org_3kLRiLfjs2e5TaVr'
        command: kubectl
        env: null
        interactiveMode: IfAvailable
        provideClusterInfo: false
